services:
  - type: web
    name: springboot-demo
    env: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: Dockerfile
    rootDir: .              # ✅ Required since 'demo/' is at repo root
    healthCheckPath: /